[versions]
agp = "8.5.1"
artifactid = "2.0.0"
kotlin = "1.9.0"
hilt = "2.51.1"
hilt-lifecycle = "1.0.0-alpha01"

coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.5.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.1"
constraintlayout = "2.1.4"
runtime = "1.7.6"
rx-kotlin = "3.0.0"
reflection = "2.0.20"
androidx-fragment = "1.8.2"
hannesdorfmann = "4.3.2"
coroutines = "1.6.4"
picasso = "2.8"
retrofit = "2.6.0"
roomversion = "2.2.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "runtime" }
artifactid = { module = "groupId:artifactId", version.ref = "artifactid" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
reflection = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "reflection"}

androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

rx-kotlin = { group = "io.reactivex.rxjava3", name = "rxkotlin", version.ref = "rx-kotlin" }
rx-android = { group = "io.reactivex.rxjava3", name = "rxandroid", version.ref = "rx-kotlin" }
androidx-frgment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidx-fragment" }

hannesdorfmann-binding = { group = "com.hannesdorfmann", name = "adapterdelegates4-kotlin-dsl", version.ref = "hannesdorfmann"}
hannesdorfmann = { group = "com.hannesdorfmann", name = "adapterdelegates4-kotlin-dsl-viewbinding", version.ref = "hannesdorfmann" }

coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit"}
retrofit-converter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit"}
picasso = { group = "com.squareup.picasso", name = "picasso", version.ref = "picasso" }

roomdb = { group = "androidx.room", name = "room-runtime", version.ref = "roomversion" }
room-katp = { group = "androidx.room", name = "room-compiler", version.ref = "roomversion" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomversion" }

daggerhilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
daggerhilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
org-jetbrains-kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
