[versions]
agp = "8.5.1"
artifactid = "2.0.0"
kotlin = "1.9.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.5.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.1"
constraintlayout = "2.1.4"
rx-kotlin = "3.0.0"
reflection = "2.0.20"
androidx-fragment = "1.8.2"
hannesdorfmann = "4.3.2"
coroutines = "1.3.1"
picasso = "2.8"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
artifactid = { module = "groupId:artifactId", version.ref = "artifactid" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
reflection = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "reflection"}

androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

rx-kotlin = { group = "io.reactivex.rxjava3", name = "rxkotlin", version.ref = "rx-kotlin" }
rx-android = { group = "io.reactivex.rxjava3", name = "rxandroid", version.ref = "rx-kotlin" }
androidx-frgment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidx-fragment" }

hannesdorfmann-binding = { group = "com.hannesdorfmann", name = "adapterdelegates4-kotlin-dsl", version.ref = "hannesdorfmann"}
hannesdorfmann = { group = "com.hannesdorfmann", name = "adapterdelegates4-kotlin-dsl-viewbinding", version.ref = "hannesdorfmann" }

coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }

picaso = { group = "com.squareup.picasso", name = "picasso", version.ref = "picasso" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "artifactid" }

