[versions]
agp = "8.5.1"
artifactid = "2.0.0"
glide = "1.0.0-beta01"
kotlin = "2.0.21"
ksp = "2.0.21-1.0.27"
hilt = "2.51.1"
hilt-comompose = "1.2.0"
hilt-lifecycle = "1.0.0-alpha01"

coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.5.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.1"
constraintlayout = "2.1.4"
okhttpBom = "4.10.0"
runtime = "1.7.6"
rx-kotlin = "3.0.0"
reflection = "2.0.20"
androidx-fragment = "1.8.2"
hannesdorfmann = "4.3.2"
coroutines = "1.7.3"
picasso = "2.8"
retrofit = "2.6.0"
roomversion = "2.7.0-beta01"
mockk = "1.13.14"
compose_boom_version = "2025.02.00"
navigation-ref = "2.8.8"
serialization = "1.8.0"
lifecycle-viewmodel = "2.7.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "runtime" }
androidx-compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-ref" }
compose-boom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose_boom_version" }
glide = { group = "com.github.bumptech.glide", name = "compose",version.ref = "glide" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }
mock = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
mock-agent = { group = "io.mockk", name = "mockk-agent", version.ref = "mockk" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttpBom" }
reflection = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "reflection"}
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle-viewmodel"}


androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

rx-kotlin = { group = "io.reactivex.rxjava3", name = "rxkotlin", version.ref = "rx-kotlin" }
rx-android = { group = "io.reactivex.rxjava3", name = "rxandroid", version.ref = "rx-kotlin" }
androidx-frgment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidx-fragment" }

hannesdorfmann-binding = { group = "com.hannesdorfmann", name = "adapterdelegates4-kotlin-dsl", version.ref = "hannesdorfmann"}
hannesdorfmann = { group = "com.hannesdorfmann", name = "adapterdelegates4-kotlin-dsl-viewbinding", version.ref = "hannesdorfmann" }

coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit"}
retrofit-converter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit"}
picasso = { group = "com.squareup.picasso", name = "picasso", version.ref = "picasso" }

roomdb = { group = "androidx.room", name = "room-runtime", version.ref = "roomversion" }
room-katp = { group = "androidx.room", name = "room-compiler", version.ref = "roomversion" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomversion" }

daggerhilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
daggerhilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
daggerhilt-compose-compiler = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-comompose" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
org-jetbrains-kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
